version: '3'
services:
  object-storage:
    image: minio/minio:latest
    container_name: object_storage
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: promotions-user
      MINIO_ROOT_PASSWORD: promotions123
    networks:
      - promotions-network
    volumes:
      - object-storage-volume:/data
  object-storage-init:
    build: ./minio
    container_name: object_storage_init
    networks:
      - promotions-network
    depends_on:
      - object-storage
  clickhouse:
    build: ./clickhouse
    container_name: promotions_app_datasource
    depends_on:
      - object-storage-init
    ports:
      - "8123:8123"
      - "9002:9000"
    networks:
      - promotions-network
    volumes:
      - datasource-volume:/var/lib/clickhouse
#  promotions_app:
#    build:
#      context: ..
#      dockerfile: ./docker-compose/promotions-app/Dockerfile
#    container_name: promotions_app
#    ports:
#      - "8080:8080"
#    networks:
#      - promotions-network
#    depends_on:
#      - clickhouse
networks:
  promotions-network:
volumes:
  object-storage-volume:
  datasource-volume: