// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/promotions/{id}": {
            "get": {
                "description": "Returns promotion by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get promotion by id"
                ],
                "summary": "Returns promotion by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Promotion"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Promotion": {
            "type": "object",
            "properties": {
                "expiration_date": {
                    "type": "string",
                    "example": "2018-08-10 12:47:53 +0200 CEST"
                },
                "id": {
                    "type": "string",
                    "example": "d9433531-5b0a-431d-82d4-b413dc34253f"
                },
                "price": {
                    "type": "number",
                    "example": 32.180885
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
